import { useEffect, useState, type FormEvent } from 'react';
import { api } from '../../api/client';
import { ApiError, type BackupJob, type BackupPolicy } from '../../core/api';

const defaults: BackupPolicy = { enabled: false, destination: '', schedule_kind: 'interval', interval_seconds: 86400, local_time: '03:00', timezone: 'UTC', retain_count: 7, retain_age_seconds: 2592000, budget_bytes: 10737418240, last_status: 'never' };

export function BackupPanel() {
  const [policy,setPolicy]=useState<BackupPolicy>(defaults);const [jobs,setJobs]=useState<BackupJob[]>([]);const [message,setMessage]=useState('');const [saving,setSaving]=useState(false);
  const [locked,setLocked]=useState<Set<string>>(new Set());
  const load=()=>api.backupStatus().then((result)=>{if(!result?.policy)return;setPolicy(result.policy);setJobs(result.jobs??[])}).catch((error)=>setMessage(error instanceof ApiError?error.message:'Backup status is unavailable.'));
  useEffect(()=>{void load();void api.settingsInventory().then((result)=>setLocked(new Set((result.settings??[]).filter((setting)=>setting.source==='environment').map((setting)=>setting.key)))).catch(()=>undefined)},[]);
  useEffect(()=>{if(!jobs.some((job)=>job.status==='queued'||job.status==='running'))return;const timer=window.setInterval(()=>void load(),1500);return()=>window.clearInterval(timer)},[jobs]);
  const save=async(event:FormEvent)=>{event.preventDefault();setSaving(true);try{const result=await api.saveBackupPolicy(policy);setPolicy(result.policy);setMessage('Backup policy saved.')}catch(error){setMessage(error instanceof ApiError?error.message:'Unable to save backup policy.')}finally{setSaving(false)}};
  const run=async()=>{try{const result=await api.runBackup();setJobs((current)=>[result.job,...current]);setMessage('Backup queued.')}catch(error){setMessage(error instanceof ApiError?error.message:'Unable to queue backup.')}};
  const cancel=async(id:string)=>{try{const result=await api.cancelBackup(id);setJobs((current)=>current.map((job)=>job.id===id?result.job:job))}catch(error){setMessage(error instanceof ApiError?error.message:'Unable to cancel backup.')}};
  const update=<K extends keyof BackupPolicy>(key:K,value:BackupPolicy[K])=>setPolicy((current)=>({...current,[key]:value}));
  return <section id="backups" className="owner-section" aria-labelledby="backups-title"><h2 id="backups-title">Backups</h2><p>Create verified copies of profiles, viewing history, settings, metadata decisions, and original downloaded artwork. Media files and temporary playback data are excluded.</p>
    {message&&<p role="status">{message}</p>}
    <form onSubmit={save}><label>Backup folder<input aria-label="Backup folder" disabled={locked.has('backup.destination')} value={policy.destination} placeholder="/mnt/backups/flixr" onChange={(event)=>update('destination',event.target.value)} /></label>
      <label><input type="checkbox" disabled={locked.has('backup.schedule')} checked={policy.enabled} onChange={(event)=>update('enabled',event.target.checked)} /> Run backups automatically</label>
      <div className="owner-columns"><label>Schedule<select disabled={locked.has('backup.schedule')} value={policy.schedule_kind} onChange={(event)=>update('schedule_kind',event.target.value as BackupPolicy['schedule_kind'])}><option value="interval">Every interval</option><option value="daily">Daily</option></select></label>{policy.schedule_kind==='interval'?<label>Hours between backups<input disabled={locked.has('backup.schedule')} type="number" min="1" max="8760" value={policy.interval_seconds/3600} onChange={(event)=>update('interval_seconds',Number(event.target.value)*3600)} /></label>:<><label>Local time<input disabled={locked.has('backup.schedule')} type="time" value={policy.local_time} onChange={(event)=>update('local_time',event.target.value)} /></label><label>Timezone<input disabled={locked.has('backup.schedule')} value={policy.timezone} onChange={(event)=>update('timezone',event.target.value)} /></label></>}</div>
      <div className="owner-columns"><label>Keep newest<input disabled={locked.has('backup.retain_count')} type="number" min="1" max="100" value={policy.retain_count} onChange={(event)=>update('retain_count',Number(event.target.value))} /></label><label>Keep for days<input disabled={locked.has('backup.retain_age')} type="number" min="1" value={policy.retain_age_seconds/86400} onChange={(event)=>update('retain_age_seconds',Number(event.target.value)*86400)} /></label><label>Storage budget (GiB)<input disabled={locked.has('backup.budget_bytes')} type="number" min="1" value={Math.round(policy.budget_bytes/1073741824)} onChange={(event)=>update('budget_bytes',Number(event.target.value)*1073741824)} /></label></div>
      <button type="submit" disabled={saving}>{saving?'Saving…':'Save backup policy'}</button> <button type="button" onClick={()=>void run()}>Back up now</button>
    </form>
    <p><strong>Last result:</strong> {policy.last_status==='never'?'No verified backup yet.':policy.last_status}{policy.last_verified_at?` · ${new Date(policy.last_verified_at*1000).toLocaleString()}`:''}</p>{policy.next_run_at&&<p><strong>Next backup:</strong> {new Date(policy.next_run_at*1000).toLocaleString()}</p>}
    <h3>Recent backup activity</h3>{jobs.length===0?<p>No backup jobs yet.</p>:<ul className="scan-jobs">{jobs.slice(0,8).map((job)=><li key={job.id}><strong>{job.trigger==='manual'?'Manual':'Scheduled'} backup</strong> · {job.status}{job.finished_at?` · ${new Date(job.finished_at*1000).toLocaleString()}`:''}{job.message&&<span> · {job.message}</span>}{(job.status==='queued'||job.status==='running')&&<button type="button" onClick={()=>void cancel(job.id)}>Cancel</button>}</li>)}</ul>}
    <details><summary>How to restore</summary><p>Stop Flixr, then run <code>flixr restore-backup --data-dir /path/to/flixr-data --archive /path/to/backup.flixr-backup</code>. Flixr verifies the archive before changing data and keeps a safety backup when replacing an installation.</p></details>
  </section>
}
